#!/usr/bin/env bash
exec 3>&1

CODE=$(curl -s -w "%{http_code}" \-o >(cat >&3) http://127.0.0.1:8080/smoke/noname -H 'Content-Type: application/erlang' --data-binary @$*)

if [[ "${CODE}" == "200" ]] ; 
then
   exit 0
else
   exit 1
fi
